apiVersion: v1
kind: Secret
metadata:
  name: prueba-vault
  annotations:
#   avp_path: avp/data/example/prueba-vault
    avp.kubernetes.io/path: "avp/data/example/prueba-vault2"
type: Opaque
stringData:
  USER_NAME: YW5nZWwK
  PASSWORD: YWd1YW50ZXNpbHZpbzIwMjIK
  USERNAME_VAULT: <username>
  MAS_DATA: bXVjaGFtYXNkYXRheXJlY29tcGxlamExMzY4cGVyb25vdGFuY29tcGxlamFlbjIwMjMK
